### ISSUE TITLE
Build Intructions

### ISSUE THREAD

**Issue by kurobeats** [netbootxyz/netboot.xyz#175] opened 2017-09-06 04:48 UTC
Just wondering if you might be able to provide build instructions for development and alike, such as:

1. install dependencies
2. git clone
3. make changes to code
4. run ./build_script.sh

**Comment by MitchRatquest** [comment] 2017-09-29 13:33
It went like this for me (on debian 9):
sudo apt-get install liblzma-dev
git clone https://github.com/antonym/netboot.xyz.git
cd netboot.xyz
cp script/prep-release.sh .
./prep-release.sh

**Comment by webairnetboot** [comment] 2017-11-07 17:19
This seems like a duplicate of [Self-hosting Instructions #26](https://github.com/antonym/netboot.xyz/issues/26 )

**Closed as completed** 2017-11-09 00:07 UTC
Labels: duplicate

**Comment by dszidi** [comment] 2019-01-31 03:11
This is not quite correct. Running the prep-release.sh fails because there are no .crt files in the repo.
