### ISSUE TITLE
Running Local?

### ISSUE THREAD

**Issue by Ttech** [netbootxyz/netboot.xyz#140] opened 2017-04-25 16:40 UTC
I love the work you've been doing on this project. 

I was wondering if I could run it locally though, because I'd like to use this in a lab. Is there a way to mirror the current work without rebuilding everything?

Thanks

**Comment by antonym** [comment] 2017-05-04 15:59
Thanks, happy it's useful!  

Yeah, I had some ideas about doing that where you'd run an Ansible playbook to get it all set up on a local machine.  I just need to find some time to dig into that.  It's on my long TODO.

**Comment by webairnetboot** [comment] 2017-11-07 17:17
This seems like a duplicate of [Self-hosting Instructions #26](https://github.com/antonym/netboot.xyz/issues/26 )

**Closed as completed** 2017-11-09 00:07 UTC
Labels: duplicate
