### ISSUE TITLE
Proxmox 

### ISSUE THREAD

**Issue by sim1** [netbootxyz/netboot.xyz#33] opened 2016-01-15 18:33 UTC
It'd be nice to add Proxmox.
Link to latest: (4.0) http://www.proxmox.com/images/download/pve/iso/proxmox-ve_4.0-0d8559d0-17.iso

**Comment by Awmusic12635** [comment] 2016-01-15 18:33
+1

**Comment by antonym** [comment] 2016-01-15 20:37
It appears to be Debian based but unfortunately, this has the fun problem of not working well with memdisk. [possible fix](https://www.reversengineered.com/2016/01/07/booting-linux-isos-with-memdisk-and-ipxe/).  I ran across this forum [post](https://forum.proxmox.com/threads/proxmox-installation-via-pxe-solution.8484/) but it involves modification of the original ISO which I'm trying to avoid doing.

**Comment by antonym** [comment] 2016-06-30 23:06
Closing this unless someone wants to chase down the maintainer to get supported added to use with memdisk/iPxe

**Comment by TomGlass** [comment] 2018-07-05 11:40
Hello,

Wondering if a couple years later this is possible?

**Comment by salanki** [comment] 2019-10-15 13:10
https://github.com/morph027/pve-iso-2-pxe would be nice to have that integrated

**Comment by antonym** [comment] 2019-10-16 03:04
This would require the maintainer of the product to host the extracted ISO for netboot.xyz to leverage.  A lot of ISOs are possible to boot but iPXE isn't the best at mounting and loading files from the mount over the network.

**Comment by wrobelda** [comment] 2020-02-17 16:39
@antonym pve-iso-2-pxe actually converts iso image to kernel and initrd images, so ISO booting is not required. Can you consider supporting it?

**Comment by thelamer** [comment] 2020-02-20 20:22
Boot snippet here: 
```
#!ipxe
imgfree
set url https://github.com/thelamer/boot-assets/releases/download/proxmox/
kernel ${url}linux26 initrd=initrd
initrd ${url}initrd
boot
```
It is not hard to do the question is if we are greenlit to host these assets.

**Comment by orange888** [comment] 2020-04-06 12:21
Please incorporate this. Thanks.

**Comment by Nickfost** [comment] 2020-07-25 05:38
+1

**Comment by thelamer** [comment] 2020-07-25 05:50
It is not a vote, it is a potential licensing issue. Just because is is possible does not make it legal IE windows.

**Comment by antonym** [comment] 2020-07-25 16:34
Closing until we can determine if this is something we could host since it does have a subscription based licensing.

**Comment by LucaDev** [comment] 2020-11-03 15:07
Proxmox is actually open source. It is released under the AGPL v3. Only support is subscription based.

**Comment by thelamer** [comment] 2020-11-03 15:12
The problem is we are essentially rehosting their built assets from their website. The demo I showed above is not built from source. We would need to at a bare minimum get their permission to do this so we don't get a dmca.

**Comment by antonym** [comment] 2020-11-03 15:23
I have sent Proxmox an e-mail to see if doing so would be considered acceptable.

**Closed** 2020-11-24 15:41 UTC
Labels: linux, memdisk
